### ISSUE TITLE
Bandwith output for graphite?

### ISSUE THREAD

**Issue by Marco-Total** [NETWAYS/check_interfaces#11]
Hi,

we installed icinga2, icingaweb2 and graphite. I'm have an Issue with graphite, the problem is, that the bandwith (MBit/s) not displayed in a graphite graph, because this check write no matching output for the bandwith?

I use the following command, to check the interface:
’/usr/lib64/nagios/plugins/check_interfaces’ ‘–community’ ‘XXXX’ ‘–hostname’ ‘172.xx.xx.xx’ ‘–lastcheck’ '$service.last_check$ ‘–perfdata’ '$service.perfdata$ ‘–regex’ '^1$'

![6339f24b094a2a8532066f548ed3181a575b3a9a](https://user-images.githubusercontent.com/6968432/81777811-ed733100-94f1-11ea-9ce9-755cdc9d3675.png)

Can you expand your script, or is there a option that can I use?

Thank you!

RUDI

**Comment by SuperPlusUser** [comment]
Hi Rudi,

you can have a look at my fork: https://github.com/SuperPlusUser/check_interfaces

With commit a45912783b01cdb27a9a11ddd98fadfcaf5f5a6b I added inBitps and outBitps to the performance data output.

**Comment by RincewindsHat** [comment]
This is now merged. Hoping to pack that up into a new releas soonish.
