### ISSUE TITLE
Temp files for perfdata

### ISSUE THREAD

**Issue by Bierchermuesli** [NETWAYS/check_interfaces#12]
is there a approach to use temporary files instead of `--lastcheck`  and` --perfdata`?

the perfdata string can be very long, GUI/Logs/Graphing Addon etc can have performance impact

**Comment by RincewindsHat** [comment]
Hi @Bierchermuesli,
Sorry for the lack of response. The problem with temporary files is, that they might actually work not so well in certain circumstances. For example, in Icinga2 different machines could execute the same check ("distributed monitoring") and Icinga2 doesn't know at all about those files, so the output might just be plain wrong, if the check switches machines.
The solution as it is, is the only one where we can mostly guarantee, that the plugin actually receives the right data.
