### ISSUE TITLE
check_interfaces vs. Ubuntu 20.04

### ISSUE THREAD

**Issue by martindemharter** [NETWAYS/check_interfaces#13]
Hi,

we started, using Ubuntu 20.04. LTS. The check compiled for Ubuntu 18.04 does not work because of libsnmp-dev including libnet-snmp.so.30 is needed and avaliable in Ubuntu 18.04. For Ubuntu 20.04. they issued libnet-snmp.so.35 which is not compatible.

Make script works for Ubuntu20.04. as well, but the check always runs into a timeout, message is: `Timeout while reading interface descriptions from localhost`

is there any chance, this will be fixed soon?

BR

Martin

**Comment by e3k** [comment]
Timeout while reading interface descriptions from localhost usually comes when snmpd is not started.
Try to check if snmpd is running.

**Comment by nick4me** [comment]
If you have problems compiling, you can also use the Thola Check plugin. It is written in Go and therefore the binary is statically compiled and hardly needs any dependencies from the operating system.

GitHub site: https://github.com/inexio/thola
Homepage: https://thola.io

**Comment by martindemharter** [comment]
> 
> 
> Timeout while reading interface descriptions from localhost usually comes when snmpd is not started.
> Try to check if snmpd is running.

This does not work. snmp relies in Ubuntu20.04 on libnet-snmp.so.35.
But the check_interfaces needs libnet-snmp.so.30. (.so.30 vs .so.35)

**Comment by manuelzambrano** [comment]
You should build a new check_interfaces on your Ubuntu20.04 as shown in the README.  I got my check_interfaces  running with  libnet-snmp.so.40 on a Deb11.

**Comment by RincewindsHat** [comment]
If that program was linked against the "wrong" library it is not surprising to see, that it won't work.
I am closing this, since this does not look like a problem to be fixed here for me.
