### ISSUE TITLE
New Release and switch to semantic versioning

### ISSUE THREAD

**Issue by martialblog** [NETWAYS/check_interfaces#20]
@RincewindsHat We shoud provide a new proper relase, the last one was on Jan 5, 2018. And might switch to semantic versioning, we use it everywhere else.

**Comment by RincewindsHat** [comment]
Jup, that's the plan. But I think I need to do some proper testing and refactoring before I am ok with releasing it.

**Comment by martialblog** [comment]
I'm glad my test-shaming is finally showing results.

**Comment by martialblog** [comment]
Closing this for now. The new release will be with semver.
