### ISSUE TITLE
[Feature]: Add support for the SHA-256 auth algorithm

### ISSUE THREAD

**Issue by jwillikers** [NETWAYS/check_interfaces#25]
### Describe the feature request

I'd like to use this on a host that uses SHA-256 for the auth algorithm, but it doesn't look like it's supported.

**Comment by martialblog** [comment]
@RincewindsHat can you have a look at this?

**Comment by martialblog** [comment]
Maybe we could extend the auth-proto flag to include a SHA256 option?

@jwillikers Pull Requests are welcome, if you want to implement this

**Comment by jwillikers** [comment]
Sweet, I'll try to find some time to add that. Should be pretty trivial since it is supported in the net-snmp library.

**Comment by RincewindsHat** [comment]
Jup, could be done in a way which would not disturb the other options.
If net-snmp supports it, this should be relatively easy.
Testing would be annoying though.

**Comment by jwillikers** [comment]
> Jup, could be done in a way which would not disturb the other options. If net-snmp supports it, this should be relatively easy. Testing would be annoying though.

@RincewindsHat I found your branch and that works for me.

**Comment by RincewindsHat** [comment]
Good to know, thanks :-)
Wanted to add the help for that option and stuff and didn't find the time since then.

**Comment by jwillikers** [comment]
I went ahead and updated the documentation and help output for you in #27.
