### ISSUE TITLE
[Feature]: Add version flag

### ISSUE THREAD

**Issue by jwillikers** [NETWAYS/check_interfaces#41]
### Describe the feature request

I'm working on packaging `check_interfaces` in Nix. There's an automated version check that can verify the programs version and that the program is running correctly. It would be great if `check_interfaces` supported a `--version` flag and reported the version and exited successfully. See the comment regarding this check in the PR [here](https://github.com/NixOS/nixpkgs/pull/349568#discussion_r1807081233).

**Comment by RincewindsHat** [comment]
Hi @jwillikers,
Good point, I will take a look at it
